### ISSUE TITLE
Change character image

### ISSUE THREAD

**Issue by fenwickjb** [CompassSoftware/AppTAG#1]
We don't want a blue dot anymore! I submitted a sheet (asset/human_ab.gif) with 4 images for a better character. You'll need to edit that to "cut" out the four different images: facing east/west/north/south.

Then update code so that every 'w' (up) button loads the north character image before moving.
And similarly for the other directions.

**Comment by berrytc1** [comment]
Changed the image and fixed the issue with the M & B key. The character now disappears when these keys are pressed
