### ISSUE TITLE
Fix bug where going back and forth between the same rooms causes roomProgress to still increment

### ISSUE THREAD

**Issue by wattsian6** [CompassSoftware/AppTAG#118]
only increment roomProgress if we discover a new room

**Comment by fenwickjb** [comment]
The roomProgress variable is being used for the returnDoor issue #129. So this is closed.

But I think the solution is to not increment but just set to a predefined value for that room.
roomProgress = 10;
Other rooms just check if roomProgress is > or < than a value they need.
