### ISSUE TITLE
Work on test Activity

### ISSUE THREAD

**Issue by rothrockre** [CompassSoftware/AppTAG#12]
Once the boards are read the test becomes available. 
-Label the boxes
-put into straight line
-add correct & wrong counter
-has to have all correct to pass
-if anything else feel free to add
-allow to retake 
-if pass go back to main room

**Comment by tyelerCromwell** [comment]
Probably take like an hour to get all the images and find pictures for the the documents

**Comment by tyelerCromwell** [comment]
moving hitboxes took a lot longer than I thought probably like 2 hours, I had some assumptions about how it worked and I was wrong

**Comment by tyelerCromwell** [comment]
But I moved the boxes in the normal map and inside the quiz, moved hit boxes and created some labels

**Comment by tyelerCromwell** [comment]
Its pretty much done now, I just need to figure out how to let players take the quiz again
