### ISSUE TITLE
Naming Scheme

### ISSUE THREAD

**Issue by fenwickjb** [CompassSoftware/AppTAG#125]
Part of Epic Story #124.

There are so many rooms and activities and then images/characters/panels for each of those that it’s very confusing.

I wonder if a common naming scheme might be helpful.
R0P1.jpg is the image for room 0 panel 1. And so on.

Also, sub folders in asset/ folder based on room might be good too.

Thoughts?

**Comment by berrytc1** [comment]
Also cleaning up code and deleting the commented code that is in each room.
