### ISSUE TITLE
Next room hole in concrete room not working properly

### ISSUE THREAD

**Issue by fenwickjb** [CompassSoftware/AppTAG#146]
During demo we could not get the round "next room" hole to work properly. We read all the info panels. When we pressed U to unlock then it worked.

**Comment by fenwickjb** [comment]
Read all panels to get two holes. Both holes enable interaction with e key. Go in jagged hole to puzzle room. Come out and read upper middle panel and not round hole does not enable interaction.

**Comment by berrytc1** [comment]
I solved this in my naming scheme issue/pull request
