### ISSUE TITLE
clean up activity completion flags

### ISSUE THREAD

**Issue by fenwickjb** [CompassSoftware/AppTAG#150]
We think a roomProgress value can be used in place of the many activity1completed types of flags. After reading first panel, roomProgress is set to higher value.

The roomProgress values: Each lesson room starts a new 1000. So zeroLesson goes from 0-999, and one_lesson from 1000-1999, etc. Each info panel can be like 5. Each activity "room" for a lesson starts at next 100. So the sorting activity is at x100 and the puzzle room is at x200, etc.

Should not ever decrement roomProgress. Main lesson rooms should set at the 1000s (e.g., roomProgress = 3000). But other items should be relative (in case the main lesson room gets moved and hence it's base number isn't 3000 anymore it is 5000). Maybe keep a variable set for the main lesson room: currentRoom = 3000. Then roomProgress = currentRoom + 100 says "first activity room in this room." And roomProgress = currentRoom + 15 says "read 3rd wall info panel in this room."

**Comment by berrytc1** [comment]
I updated the roomProgress variable so that it increments with certain progress of the player. It is in branch roomProgess-Issue150 and is merged in master
