### ISSUE TITLE
AccountEqn room (Room3)

### ISSUE THREAD

**Issue by fenwickjb** [CompassSoftware/AppTAG#168]
Need to get this room in order:

- [ ] wall info panels known
- [ ] activities figured out

**Comment by JerichoSM** [comment]
Thinking ahead a bit, just to keep it in mind for myself when we get to this, have we designed any activities to use for this room and its information? What new information does it present? I remember seeing "Monster" sprites in the asset data at some point, could we do a "Monster Fight" activity with correct answers dealing damage? Just an idea.

**Comment by fenwickjb** [comment]
It's a great idea. I think it is dependent on some global scoring value, like coins or life points. I'll create an issue to add coins. So go look for that! After coins, if we want, we can add life points or hearts or damage or whatever.

**Comment by fenwickjb** [comment]
On branch: iss168

got panels 1 and 2 redone: Tue Feb 18th.
