### ISSUE TITLE
Add coins for completing activities

### ISSUE THREAD

**Issue by fenwickjb** [CompassSoftware/AppTAG#174]
We have a "global variable" in the roomProgress so we can do another one for coinCount.  Then achieving certain things can earn coins. And we can deposit coin images that Accacio can engage with too. (I have such an image in the parents activity Room2Activity2.)

Can we have a timer to know how quickly they complete an activity? That would allow more coins for solving it faster!

- [x] add global coinCount variable
- [x] add a coin image for when earn a coin (like how the E image appears overhead)
- [x] maybe add an animation for that overhead coin image for it to "rotate" or something
- [x] need the coin image to be accompanied by a coin sound
- [ ] need the "backpack" feature working to show how many coins have been accumulated
- [x] need to identify "coin earning opportunities"

**Comment by fenwickjb** [comment]
Coin earning opportunities:

- Let's have a coin object in the very first room as an inducement to learning how to move Accacio
- Earn a coin for reading the first room wall panel (actually, it's more when the next-room-hole is first  shown)
- Earn a coin if read all the screens of a multi-screen wall panel.
- Earn a coin if read all the wall info panels (that is, unlocking an activity)
- Earn coins for speed of accomplishing certain activities

**Comment by fenwickjb** [comment]
Thoughts on git branching...

We want master to get ALL of these at once (coin variable, backpack showing count, coin animation, and some basic coin earning opportunities enabled). 

So let's create a coin branch off master for all of this. Then a branch off of THAT coin branch for each of the tasks noted above in the issue. Merge them back into the coin branch when that piece is working. We can tolerate it partially done (e.g., no backpack count visible yet) but users (master branch) can not.

**Comment by JerichoSM** [comment]
Alright, I've created the branch. If suitable, please refer to this comment (or somewhere more clear if you can find/allow it) to create further branches.
Using the list of todo on this issue, create branches with naming conventions as follow:
**Sub-Master Branch** "iss_174":

Branch "iss_174a": add global coinCount variable and identify coin earning opportunities. Increase cointCount global variable in every identified opportunity.

Branch "iss_174b": add a coin image for when earn a coin above head and potentially animate it to rotate to add character.

Branch "iss_174c": add sound to accompany coin collection

Branch "iss_174d": finish backpack feature to include coin count

**Comment by JerichoSM** [comment]
I am speculating that iss_174c can be compounded into iss_174b, 
and
iss_174d can be compounded into iss_174a due to the backpack using the global coinCount Variable. 
Let me know what you think. I'm going to work on iss_174b, since I've been researching implementation of animations for sprite images.

**Comment by upchurchzb** [comment]
Forgoing bag implementation. Adding coin count to top left of the level instead for now.
