### ISSUE TITLE
Parent Activity cleanups

### ISSUE THREAD

**Issue by fenwickjb** [CompassSoftware/AppTAG#182]
A couple items to fix in the parent activity buildBlockAct2.js.

- [x] Add correct/wrong sounds for interacting with the financial statements.

- [x] Fix the parent talking images (light blue did not transparencify well)

- [x] Update info box that shows up after collecting coin to use new coin image. (Can find coin image in branch 174 assets/Coin)

**Comment by upchurchzb** [comment]
I have fixed the transparencies for the blue text boxes, but now it appears the sizes are messed up. Will have to adjust the scaling for those.

**Comment by fenwickjb** [comment]
Sweet. There is a setScales method in the JS room file.

**Comment by upchurchzb** [comment]
Alrighty, I've fixed the scales for the images. question 2 is not quite as clear, but I don't think that's as big of a deal right now. setting pull request for branch iss_182 now.
