### ISSUE TITLE
character image change bug 1

### ISSUE THREAD

**Issue by fenwickjb** [CompassSoftware/AppTAG#21]
Bug issue related to #1.

* Basic idea is to replace this.character with 4 characters (this.character_north, etc.) each with its own image. 
* All four "move" together, so down/south decreases y position by 5 for all of them. 
* But only one is "visible" (alpha == 1). So down/south sets alphas to this.character_south to 1 and others to 0.
* Since all have same position (but only one is visible) when needing to check position (e.g. to see if in interaction zone of something else) then can use any. But should make a convention to always check one (maybe this.character_north). 
* There are a couple of places (M key is down, B key is down) where this.character is still being used but it should be all four! AND THEN how to know which was visible after M, B key released??

**Comment by berrytc1** [comment]
Made the character-movable false when the M & B key is pressed. Also made each image alpha zero when these two keys are pressed. 



Time Taken: 10 minutes.
